---
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mohamedwaleed/spring-cloud-poc.git
          searchPaths: configData
      label: master

server:
  port: 8001
